name: secure_control_panel
description: CRM-based staff control system

publish_to: 'none' 

version: 0.0.1+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  desktop_window: ^0.4.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: MacPawFixel
      fonts:
        - asset: assets/fonts/MacPawFixel/MacPawFixelText-Bold.ttf